\connect pokemon
INSERT INTO items.items (item_name, item_description, item_price) 
VALUES 
('Master Ball', 'The best Ball with the ultimate level of performance. It will catch any wild Pokémon without fail.', 0),
('Ultra Ball', 'An ultra-performance Ball that provides a higher Pokémon catch rate than a Great Ball.', 1200),
('Great Ball', 'A good, high-performance Ball that provides a higher Pokémon catch rate than a standard Poké Ball.', 600),
('Poké Ball', 'A device for catching wild Pokémon. It is thrown like a ball at the target. It is designed as a capsule system.', 200),
('Safari Ball', 'A special Poké Ball that is used only in the Great Marsh. It is decorated in a camouflage pattern.', 0),
('Net Ball', 'A somewhat different Poké Ball that works especially well on Water- and Bug-type Pokémon.', 1000),
('Dive Ball', 'A somewhat different Poké Ball that works especially well on Pokémon that live underwater.', 1000),
('Nest Ball', 'A somewhat different Poké Ball that works especially well on weaker Pokémon in the wild.', 1000),
('Repeat Ball', 'A somewhat different Poké Ball that works especially well on Pokémon species that were previously caught.', 1000),
('Timer Ball', 'A somewhat different BALL that becomes progressively better the more turns there are in a battle.', 1000),
('Luxury Ball', 'A comfortable Poké Ball that makes a caught wild Pokémon quickly grow friendly.', 1000),
('Premier Ball', 'A somewhat rare Poké Ball that has been specially made to commemorate an event of some sort.', 0),
('Dusk Ball', 'A somewhat different Poké Ball that makes it easier to catch wild Pokémon at night or in dark places like caves.', 1000),
('Heal Ball', 'A remedial Poké Ball that restores the caught Pokémon''s HP and eliminates any status problem.', 300),
('Quick Ball', 'A somewhat different Poké Ball that provides a better catch rate if it is used at the start of a wild encounter.', 1000),
('Cherish Ball', 'A quite rare Poké Ball that has been specially crafted to commemorate an occasion of some sort.', 0),
('Potion', 'Restores 20 HP.', 300),
('Antidote', 'A spray-type medicine. It lifts the effect of poison from one Pokémon.', 100),
('Burn Heal', 'A spray-type medicine. It heals a single Pokémon that is suffering from a burn.', 250),
('Ice Heal', 'A spray-type medicine. It defrosts a Pokémon that has been frozen solid.', 250),
('Awakening', 'A spray-type medicine. It awakens a Pokémon from the clutches of sleep.', 250),
('Paralyze Heal', 'A spray-type medicine. It eliminates paralysis from a single Pokémon.', 250),
('Full Restore', 'A medicine that fully restores the HP and heals any status problems of a single Pokémon.', 3000),
('Max Potion', 'Fully restores HP.', 2500),
('Hyper Potion', 'Restores 120 HP.', 1500),
('Super Potion', 'Restores 60 HP.', 700),
('Full Heal', 'A spray-type medicine. It heals all the status problems of a single Pokémon.', 600),
('Revive', 'A medicine that revives a fainted Pokémon. It restores half the Pokémon''s maximum HP.', 1500),
('Max Revive', 'A medicine that revives a fainted Pokémon. It fully restores the Pokémon''s HP.', 4000),
('Fresh Water', 'Restores 30 HP.', 200),
('Soda Pop', 'Restores 50 HP.', 300),
('Lemonade', 'Restores 70 HP.', 350),
('Moomoo Milk', 'Milk with a very high nutrition content. It restores the HP of one Pokémon by 100 points.', 500),
('Energy Powder', 'Restores 60 HP but lowers Friendship.', 500),
('Energy Root', 'Restores 120 HP but lowers Friendship.', 800),
('Heal Powder', 'Heals all status problems, but lowers Friendship.', 450),
('Revival Herb', 'Revives a Pokémon to max HP, but lowers Friendship.', 2800),
('Ether', 'It restores the PP of a Pokémon''s selected move by a maximum of 10 points.', 1200),
('Max Ether', 'It fully restores the PP of a single selected move that has been learned by the target Pokémon.', 2000),
('Elixir', 'It restores the PP of all the moves learned by the targeted Pokémon by 10 points each.', 3000),
('Max Elixir', 'It fully restores the PP of all the moves learned by the targeted Pokémon.', 4000),
('Lava Cookie', 'Heals all major status conditions.', 200),
('Berry Juice', 'A 100% pure juice made of Berries. It restores the HP of one Pokémon by just 20 points.', 100),
('Sacred Ash', 'It revives all fainted Pokémon. In doing so, it also fully restores their HP.', 3000),
('HP Up', 'Increases HP EVs by 10.', 9800),
('Protein', 'Increases Attack EVs by 10.', 9800),
('Iron', 'Increases Defense EVs by 10.', 9800),
('Carbos', 'Increases Speed EVs by 10.', 9800),
('Calcium', 'Increases Special Attack EVs by 10.', 9800),
('Rare Candy', 'A candy that is packed with energy. It raises the level of a single Pokémon by one.', 4800),
('PP Up', 'It slightly raises the maximum PP of a selected move that has been learned by the target Pokémon.', 2000),
('Zinc', 'Increases Special Defense EVs by 10.', 9800),
('PP Max', 'It maximally raises the top PP of a selected move that has been learned by the target Pokémon.', 9800),
('Old Gateau', 'Heals all major status conditions.', 200),
('Guard Spec.', 'Prevents stat reduction for five turns.', 700),
('Dire Hit', 'Raises critical-hit ratio of a Pokémon in battle.', 650),
('X Attack', 'Raises Attack of a Pokémon in battle.', 2500),
('X Defense', 'Raises Defense of a Pokémon in battle.', 2500),
('X Speed', 'Raises Speed of a Pokémon in battle.', 2500),
('X Accuracy', 'Raises Accuracy of a Pokémon in battle.', 2500),
('X Sp. Atk', 'Raises Special Attack of a Pokémon in battle.', 2500),
('X Sp. Def', 'Raises Special Defense of a Pokémon in battle.', 2500),
('Poké Doll', 'A doll that attracts Pokémon. Use it to flee from any battle with a wild Pokémon.', 250),
('Fluffy Tail', 'An item that attracts Pokémon. Use it to flee from any battle with a wild Pokémon.', 500),
('Blue Flute', 'A toy flute made from blue glass. A maniac will buy it for a high price.', 1000),
('Yellow Flute', 'A toy flute made from yellow glass. A maniac will buy it for a high price.', 1000),
('Red Flute', 'A toy flute made from red glass. A maniac will buy it for a high price.', 1000),
('Black Flute', 'A toy flute made from black glass. A maniac will buy it for a high price.', 1000),
('White Flute', 'A toy flute made from white glass. A maniac will buy it for a high price.', 1000),
('Shoal Salt', 'Pure salt that can be discovered deep inside the Shoal Cave. A maniac will buy it for a high price.', 7000),
('Shoal Shell', 'A pretty seashell that can be found deep inside the Shoal Cave. A maniac will buy it for a high price.', 7000),
('Red Shard', 'A small red shard. It appears to be from some sort of implement made long ago.', 1000),
('Blue Shard', 'A small blue shard. It appears to be from some sort of implement made long ago.', 1000),
('Yellow Shard', 'A small yellow shard. It appears to be from some sort of implement made long ago.', 1000),
('Green Shard', 'A small green shard. It appears to be from some sort of implement made long ago.', 1000),
('Super Repel', 'An item that prevents weak wild Pokémon from appearing for 200 steps after its use.', 500),
('Max Repel', 'An item that prevents weak wild Pokémon from appearing for 250 steps after its use.', 700),
('Escape Rope', 'A long, durable rope. Use it to escape instantly from a cave or a dungeon.', 550),
('Repel', 'An item that prevents weak wild Pokémon from appearing for 100 steps after its use.', 350),
('Sun Stone', 'Evolves certain species of Pokémon.', 1000),
('Moon Stone', 'Evolves certain species of Pokémon.', 1000),
('Fire Stone', 'Evolves certain species of Pokémon.', 1000),
('Thunder Stone', 'Evolves certain species of Pokémon.', 1000),
('Water Stone', 'Evolves certain species of Pokémon.', 1000),
('Leaf Stone', 'Evolves certain species of Pokémon.', 1000),
('Tiny Mushroom', 'A small and rare mushroom. It is sought after by collectors.', 250),
('Big Mushroom', 'A large and rare mushroom. It is sought after by collectors.', 5000),
('Pearl', 'A somewhat-small pearl that sparkles in a pretty silver color. It can be sold cheaply to shops.', 500),
('Big Pearl', 'A quite-large pearl that sparkles in a pretty silver color. It can be sold at a high price to shops.', 4000),
('Stardust', 'Lovely, red-colored sand with a loose, silky feel. It can be sold at a high price to shops.', 1000),
('Star Piece', 'A shard of a pretty gem that sparkles in a red color. It can be sold at a high price to shops.', 10000),
('Nugget', 'A nugget of pure gold that gives off a lustrous gleam. It can be sold at a high price to shops.', 5000),
('Heart Scale', 'A pretty, heart-shaped scale that is extremely rare. It glows faintly in the colors of the rainbow.', 100),
('Honey', 'A sweet honey with a lush aroma that attracts wild Pokémon when it is used in grass, caves, or on special trees.', 100),
('Growth Mulch', 'A fertilizer to be spread on soft soil in regions where Berries are grown. A maniac will buy it for a high price.', 1000),
('Damp Mulch', 'A fertilizer to be spread on soft soil in regions where Berries are grown. A maniac will buy it for a high price.', 1000),
('Stable Mulch', 'A fertilizer to be spread on soft soil in regions where Berries are grown. A maniac will buy it for a high price.', 1000),
('Gooey Mulch', 'A fertilizer to be spread on soft soil in regions where Berries are grown. A maniac will buy it for a high price.', 0),
('Root Fossil', 'A fossil of an ancient Pokémon that lived in the sea. It appears to be part of a plant root.', 0),
('Claw Fossil', 'A fossil of an ancient Pokémon that lived in the sea. It appears to be part of a claw.', 0),
('Dome Fossil', 'A fossil of an ancient Pokémon that lived in the sea. It appears to be part of a shell.', 0),
('Old Amber', 'A piece of amber that contains the genetic material of an ancient Pokémon. It is clear with a reddish tint.', 0),
('Armor Fossil', 'A fossil from a prehistoric Pokémon that lived on the land. It appears to be part of a collar.', 0),
('Skull Fossil', 'A fossil from a prehistoric Pokémon that lived on the land. It appears to be part of a head.', 0),
('Rare Bone', 'A bone that is extremely valuable for Pokémon archeology. It can be sold for a high price to shops.', 5000),
('Shiny Stone', 'Evolves certain species of Pokémon.', 3000),
('Dusk Stone', 'Evolves certain species of Pokémon.', 1000),
('Dawn Stone', 'Evolves certain species of Pokémon.', 1000),
('Oval Stone', 'Evolves Happiny when held.', 0),
('Odd Keystone', 'A vital item that is needed to keep a stone tower from collapsing. Voices can be heard from it occasionally.', 0),
('Griseous Orb', 'Increases the power of Dragon- and Ghost-type moves when held by Giratina, and changes it to Origin Forme.', 0),
('Douse Drive', 'Changes Techno Blast to a Water-type move when held by Genesect.', 0),
('Shock Drive', 'Changes Techno Blast to an Electric-type move when held by Genesect.', 0),
('Burn Drive', 'Changes Techno Blast to a Fire-type move when held by Genesect.', 0),
('Chill Drive', 'Changes Techno Blast to an Ice-type move when held by Genesect.', 0),
('Sweet Heart', 'Very sweet chocolate. It restores the HP of one Pokémon by only 20 points.', 0),
('Adamant Orb', 'Increases the power of Dragon- and Steel-type moves when held by Dialga.', 0),
('Lustrous Orb', 'Increases the power of Dragon- and Water-type moves when held by Palkia.', 0),
('Cheri Berry', 'If held by a Pokémon, it recovers from paralysis.', 20),
('Chesto Berry', 'If held by a Pokémon, it recovers from sleep.', 20);