INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Master Ball', 'The best Ball with the ultimate level of performance. It will catch any wild Pokémon without fail.', 0);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Ultra Ball', 'An ultra-performance Ball that provides a higher Pokémon catch rate than a Great Ball.', 1200);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Great Ball', 'A good, high-performance Ball that provides a higher Pokémon catch rate than a standard Poké Ball.', 600);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Poké Ball', 'A device for catching wild Pokémon. It is thrown like a ball at the target. It is designed as a capsule system.', 200);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Safari Ball', 'A special Poké Ball that is used only in the Great Marsh. It is decorated in a camouflage pattern.', 0);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Net Ball', 'A somewhat different Poké Ball that works especially well on Water- and Bug-type Pokémon.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Dive Ball', 'A somewhat different Poké Ball that works especially well on Pokémon that live underwater.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Nest Ball', 'A somewhat different Poké Ball that works especially well on weaker Pokémon in the wild.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Repeat Ball', 'A somewhat different Poké Ball that works especially well on Pokémon species that were previously caught.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Timer Ball', 'A somewhat different BALL that becomes progressively better the more turns there are in a battle.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Luxury Ball', 'A comfortable Poké Ball that makes a caught wild Pokémon quickly grow friendly.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Premier Ball', 'A somewhat rare Poké Ball that has been specially made to commemorate an event of some sort.', 0);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Dusk Ball', 'A somewhat different Poké Ball that makes it easier to catch wild Pokémon at night or in dark places like caves.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Heal Ball', 'A remedial Poké Ball that restores the caught Pokémon''s HP and eliminates any status problem.', 300);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Quick Ball', 'A somewhat different Poké Ball that provides a better catch rate if it is used at the start of a wild encounter.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Cherish Ball', 'A quite rare Poké Ball that has been specially crafted to commemorate an occasion of some sort.', 0);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Potion', 'Restores 20 HP.', 300);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Antidote', 'A spray-type medicine. It lifts the effect of poison from one Pokémon.', 100);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Burn Heal', 'A spray-type medicine. It heals a single Pokémon that is suffering from a burn.', 250);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Ice Heal', 'A spray-type medicine. It defrosts a Pokémon that has been frozen solid.', 250);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Awakening', 'A spray-type medicine. It awakens a Pokémon from the clutches of sleep.', 250);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Paralyze Heal', 'A spray-type medicine. It eliminates paralysis from a single Pokémon.', 250);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Full Restore', 'A medicine that fully restores the HP and heals any status problems of a single Pokémon.', 3000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Max Potion', 'Fully restores HP.', 2500);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Hyper Potion', 'Restores 120 HP.', 1500);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Super Potion', 'Restores 60 HP.', 700);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Full Heal', 'A spray-type medicine. It heals all the status problems of a single Pokémon.', 600);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Revive', 'A medicine that revives a fainted Pokémon. It restores half the Pokémon''s maximum HP.', 1500);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Max Revive', 'A medicine that revives a fainted Pokémon. It fully restores the Pokémon''s HP.', 4000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Fresh Water', 'Restores 30 HP.', 200);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Soda Pop', 'Restores 50 HP.', 300);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Lemonade', 'Restores 70 HP.', 350);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Moomoo Milk', 'Milk with a very high nutrition content. It restores the HP of one Pokémon by 100 points.', 500);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Energy Powder', 'Restores 60 HP but lowers Friendship.', 500);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Energy Root', 'Restores 120 HP but lowers Friendship.', 800);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Heal Powder', 'Heals all status problems, but lowers Friendship.', 450);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Revival Herb', 'Revives a Pokémon to max HP, but lowers Friendship.', 2800);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Ether', 'It restores the PP of a Pokémon''s selected move by a maximum of 10 points.', 1200);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Max Ether', 'It fully restores the PP of a single selected move that has been learned by the target Pokémon.', 2000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Elixir', 'It restores the PP of all the moves learned by the targeted Pokémon by 10 points each.', 3000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Max Elixir', 'It fully restores the PP of all the moves learned by the targeted Pokémon.', 4000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Lava Cookie', 'Heals all major status conditions.', 200);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Berry Juice', 'A 100% pure juice made of Berries. It restores the HP of one Pokémon by just 20 points.', 100);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Sacred Ash', 'It revives all fainted Pokémon. In doing so, it also fully restores their HP.', 3000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('HP Up', 'Increases HP EVs by 10.', 9800);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Protein', 'Increases Attack EVs by 10.', 9800);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Iron', 'Increases Defense EVs by 10.', 9800);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Carbos', 'Increases Speed EVs by 10.', 9800);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Calcium', 'Increases Special Attack EVs by 10.', 9800);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Rare Candy', 'A candy that is packed with energy. It raises the level of a single Pokémon by one.', 4800);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('PP Up', 'It slightly raises the maximum PP of a selected move that has been learned by the target Pokémon.', 2000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Zinc', 'Increases Special Defense EVs by 10.', 9800);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('PP Max', 'It maximally raises the top PP of a selected move that has been learned by the target Pokémon.', 9800);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Old Gateau', 'Heals all major status conditions.', 200);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Guard Spec.', 'Prevents stat reduction for five turns.', 700);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Dire Hit', 'Raises critical-hit ratio of a Pokémon in battle.', 650);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('X Attack', 'Raises Attack of a Pokémon in battle.', 2500);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('X Defense', 'Raises Defense of a Pokémon in battle.', 2500);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('X Speed', 'Raises Speed of a Pokémon in battle.', 2500);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('X Accuracy', 'Raises Accuracy of a Pokémon in battle.', 2500);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('X Sp. Atk', 'Raises Special Attack of a Pokémon in battle.', 2500);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('X Sp. Def', 'Raises Special Defense of a Pokémon in battle.', 2500);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Poké Doll', 'A doll that attracts Pokémon. Use it to flee from any battle with a wild Pokémon.', 250);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Fluffy Tail', 'An item that attracts Pokémon. Use it to flee from any battle with a wild Pokémon.', 500);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Blue Flute', 'A toy flute made from blue glass. A maniac will buy it for a high price.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Yellow Flute', 'A toy flute made from yellow glass. A maniac will buy it for a high price.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Red Flute', 'A toy flute made from red glass. A maniac will buy it for a high price.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Black Flute', 'A toy flute made from black glass. A maniac will buy it for a high price.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('White Flute', 'A toy flute made from white glass. A maniac will buy it for a high price.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Shoal Salt', 'Pure salt that can be discovered deep inside the Shoal Cave. A maniac will buy it for a high price.', 7000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Shoal Shell', 'A pretty seashell that can be found deep inside the Shoal Cave. A maniac will buy it for a high price.', 7000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Red Shard', 'A small red shard. It appears to be from some sort of implement made long ago.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Blue Shard', 'A small blue shard. It appears to be from some sort of implement made long ago.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Yellow Shard', 'A small yellow shard. It appears to be from some sort of implement made long ago.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Green Shard', 'A small green shard. It appears to be from some sort of implement made long ago.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Super Repel', 'An item that prevents weak wild Pokémon from appearing for 200 steps after its use.', 500);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Max Repel', 'An item that prevents weak wild Pokémon from appearing for 250 steps after its use.', 700);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Escape Rope', 'A long, durable rope. Use it to escape instantly from a cave or a dungeon.', 550);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Repel', 'An item that prevents weak wild Pokémon from appearing for 100 steps after its use.', 350);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Sun Stone', 'Evolves certain species of Pokémon.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Moon Stone', 'Evolves certain species of Pokémon.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Fire Stone', 'Evolves certain species of Pokémon.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Thunder Stone', 'Evolves certain species of Pokémon.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Water Stone', 'Evolves certain species of Pokémon.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Leaf Stone', 'Evolves certain species of Pokémon.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Tiny Mushroom', 'A small and rare mushroom. It is sought after by collectors.', 250);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Big Mushroom', 'A large and rare mushroom. It is sought after by collectors.', 5000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Pearl', 'A somewhat-small pearl that sparkles in a pretty silver color. It can be sold cheaply to shops.', 500);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Big Pearl', 'A quite-large pearl that sparkles in a pretty silver color. It can be sold at a high price to shops.', 4000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Stardust', 'Lovely, red-colored sand with a loose, silky feel. It can be sold at a high price to shops.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Star Piece', 'A shard of a pretty gem that sparkles in a red color. It can be sold at a high price to shops.', 10000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Nugget', 'A nugget of pure gold that gives off a lustrous gleam. It can be sold at a high price to shops.', 5000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Heart Scale', 'A pretty, heart-shaped scale that is extremely rare. It glows faintly in the colors of the rainbow.', 100);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Honey', 'A sweet honey with a lush aroma that attracts wild Pokémon when it is used in grass, caves, or on special trees.', 100);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Growth Mulch', 'A fertilizer to be spread on soft soil in regions where Berries are grown. A maniac will buy it for a high price.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Damp Mulch', 'A fertilizer to be spread on soft soil in regions where Berries are grown. A maniac will buy it for a high price.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Stable Mulch', 'A fertilizer to be spread on soft soil in regions where Berries are grown. A maniac will buy it for a high price.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Gooey Mulch', 'A fertilizer to be spread on soft soil in regions where Berries are grown. A maniac will buy it for a high price.', 0);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Root Fossil', 'A fossil of an ancient Pokémon that lived in the sea. It appears to be part of a plant root.', 0);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Claw Fossil', 'A fossil of an ancient Pokémon that lived in the sea. It appears to be part of a claw.', 0);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Dome Fossil', 'A fossil of an ancient Pokémon that lived in the sea. It appears to be part of a shell.', 0);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Old Amber', 'A piece of amber that contains the genetic material of an ancient Pokémon. It is clear with a reddish tint.', 0);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Armor Fossil', 'A fossil from a prehistoric Pokémon that lived on the land. It appears to be part of a collar.', 0);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Skull Fossil', 'A fossil from a prehistoric Pokémon that lived on the land. It appears to be part of a head.', 0);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Rare Bone', 'A bone that is extremely valuable for Pokémon archeology. It can be sold for a high price to shops.', 5000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Shiny Stone', 'Evolves certain species of Pokémon.', 3000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Dusk Stone', 'Evolves certain species of Pokémon.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Dawn Stone', 'Evolves certain species of Pokémon.', 1000);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Oval Stone', 'Evolves Happiny when held.', 0);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Odd Keystone', 'A vital item that is needed to keep a stone tower from collapsing. Voices can be heard from it occasionally.', 0);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Griseous Orb', 'Increases the power of Dragon- and Ghost-type moves when held by Giratina, and changes it to Origin Forme.', 0);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Douse Drive', 'Changes Techno Blast to a Water-type move when held by Genesect.', 0);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Shock Drive', 'Changes Techno Blast to an Electric-type move when held by Genesect.', 0);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Burn Drive', 'Changes Techno Blast to a Fire-type move when held by Genesect.', 0);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Chill Drive', 'Changes Techno Blast to an Ice-type move when held by Genesect.', 0);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Sweet Heart', 'Very sweet chocolate. It restores the HP of one Pokémon by only 20 points.', 0);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Adamant Orb', 'Increases the power of Dragon- and Steel-type moves when held by Dialga.', 0);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Lustrous Orb', 'Increases the power of Dragon- and Water-type moves when held by Palkia.', 0);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Cheri Berry', 'If held by a Pokémon, it recovers from paralysis.', 20);
INSERT INTO items.items (item_name, item_description, item_price) VALUES ('Chesto Berry', 'If held by a Pokémon, it recovers from sleep.', 20);
