\connect pokemon

INSERT INTO pokemon.abilities (ability_name, ability_description) 
VALUES 
('Adaptability', 'The Pokemon''s STAB modifier becomes 2x.'),
('Aerilate', 'Turns all of this Pokemon''s Normal-typed attacks into Flying-type and deals 1.3x damage. Does not affect Hidden Power.'),
('Aftermath', 'Deals 25% damage when KOed by contact damage.'),
('Air Lock', 'Blocks the effects of weather.'),
('Analytic', 'Raises the power of all moves by 30% if the wielder moves last.'),
('Anger Point', 'Raises Attack to +6 if struck by a critical hit.'),
('Anticipation', 'Alerts the Pokemon of certain dangerous moves.'),
('Arena Trap', 'Prevents switching and increases wild encounter rate.'),
('Aroma Veil', 'Protects allies from attacks that limit their move choices.'),
('Aura Break', 'Reverses the effects of Dark Aura and Fairy Aura.'),
('Bad Dreams', 'Deals 12.5% damage to sleeping opponents per turn.'),
('Battle Armor', 'Prevents critical hits.'),
('Big Pecks', 'The wielder''s Defense cannot be lowered.'),
('Blaze', 'Boosts power of Fire-type moves 50% when at 1/3 of max HP or less.'),
('Bulletproof', 'This Pokemon is protected from some Ball and Bomb moves.'),
('Cheek Pouch', 'Increases HP when this Pokemon consumes a berry.'),
('Chlorophyll', 'Speed doubles in sun.'),
('Clear Body', 'Stops the enemy from lowering this Pokemon''s stats.'),
('Cloud Nine', 'Blocks the effects of weather.'),
('Color Change', 'Changes user''s type to type of last attack that hit this Pokemon.'),
('Competitive', 'Raises the user''s Special Attack stat by two stages when a stat is lowered, including the Special Attack stat. This does not include self-induced stat drops like those from Close Combat.'),
('Compound Eyes', 'Raises accuracy by 30% and increases the probability of wild Pokemon holding items.'),
('Contrary', 'The wielder''s stat changes are reversed.'),
('Cursed Body', 'The wielder has a 30% chance to disable any move that hits it.'),
('Cute Charm', 'Can infatuate Pokemon of opposite gender when struck and increases their wild encounter rate.'),
('Damp', 'Prevents the use of Self-Destruct or Explosion.'),
('Dark Aura', 'Increases the power of all Dark-type moves in battle to 1.3x.'),
('Defeatist', 'Halves the wielder''s Attack and Special Attack if its HP drops below 50%.'),
('Defiant', 'Boosts Attack by two stages for every stat drop.'),
('Delta Stream', 'Summons Strong Winds until Pokemon leaves battle. Electric/Ice/Rock moves do half damage and Weather changing moves/abilities fail, except for Primordial Sea and Desolate Land.'),
('Desolate Land', 'Summons Heavy Sun until Pokemon leaves battle. Water-type moves and weather changing moves/abilities fail, except for Primordial Sea and Delta Stream.'),
('Download', 'User gets a stat boost depending on its opponent''s stats.'),
('Drizzle', 'Summons rain.'),
('Drought', 'Summons sun.'),
('Dry Skin', 'User absorbs Water-type attacks and has a weakness to Fire-type moves. Heals in rain and is damaged by sun.'),
('Early Bird', 'Reduces sleep time by 50%.'),
('Effect Spore', 'Induces paralysis, poison, or sleep on contact.'),
('Fairy Aura', 'Increases the power of all Fairy-type moves in battle to 1.3x.'),
('Filter', 'Reduces damage from super effective hits by 1/4.'),
('Flame Body', 'Enemies'' contact moves have a 30% chance to burn them. Halves the amount of steps required to hatch Eggs.'),
('Flare Boost', 'Special Attack is increased by 50% when burned.'),
('Flash Fire', 'Grants immunity to Fire and increases Fire''s power 50% when hit by a Fire move.'),
('Flower Gift', 'Raises Attack and Special Defense of this Pokemon and its partners in sun.'),
('Flower Veil', 'Prevents lowering of ally Grass-type Pokemon''s stats.'),
('Forecast', 'Changes type according to weather.'),
('Forewarn', 'Tells which of the opponent''s moves has the highest Base Power.'),
('Friend Guard', 'Reduces damage done to a teammate by 25%.'),
('Frisk', 'Reveals the foe''s items.'),
('Fur Coat', 'Halves the damage done to this Pokemon by physical attacks.'),
('Gale Wings', 'This Pokemon''s Flying-type moves have their priority increased by 1.'),
('Gluttony', 'Consumes pinch Berries at 50% HP or less.'),
('Gooey', 'Contact with this Pokemon decreases the attacker''s Speed by 1 stage.'),
('Grass Pelt', 'This Pokemon''s Defense is boosted by 50% in Grassy Terrain'),
('Guts', 'Attack is increased 50% when afflicted by a non-volatile status.'),
('Harvest', 'After each turn, the wielder may receive the Berry it used at a 50% chance (100% if in sun).'),
('Healer', '30% chance to heal an adjacent teammate of a status condition every turn.'),
('Heatproof', 'Reduces Fire damage 50%.'),
('Heavy Metal', 'The wielder''s weight is doubled.'),
('Honey Gather', 'Adds a chance of finding Honey after each in-game battle.'),
('Huge Power', 'Doubles Attack.'),
('Hustle', 'Physical moves do 50% more damage at the cost of 20% accuracy. Increases wild encounter rate with higher level Pokemon.'),
('Hydration', 'Heals status effects in rain.'),
('Hyper Cutter', 'Prevents the enemy from lowering this Pokemon''s Attack. Increases Cut''s area of effect.'),
('Ice Body', 'Heals 1/16 of max HP in hail.'),
('Illuminate', 'Increases wild encounter rate (no effect in battles).'),
('Illusion', 'The wielder appears as the last Pokemon in the party to the opponent.'),
('Immunity', 'This Pokemon cannot be poisoned.'),
('Imposter', 'The wielder transforms into the opponent when it switches in.'),
('Infiltrator', 'The wielder bypasses the foe''s Light Screen, Reflect, Mist, Safeguard, and Substitute.'),
('Inner Focus', 'Prevents flinching.'),
('Insomnia', 'Prevents sleep.'),
('Intimidate', 'Lowers the foe''s Attack by 1 stage. Decreases wild encounter rate.'),
('Iron Barbs', 'Deals 1/8 recoil damage when the opponent makes contact.'),
('Iron Fist', 'Increases the power of punching moves by 20%.'),
('Justified', 'Raises Attack by one stage when hit by a Dark-type move.'),
('Keen Eye', 'Pokemon''s accuracy cannot be lowered. Opponent''s evasion boosts are ignored. Decreases wild encounter rate.'),
('Klutz', 'This Pokemon both is unaffected by and will not utilize held items.'),
('Leaf Guard', 'Prevents status effects in sun.'),
('Levitate', 'This Pokemon is immune to Ground-type moves.'),
('Light Metal', 'The wielder''s weight is halved.'),
('Lightningrod', 'All Electric-type attacks target this Pokemon. Grants immunity to Electric-type moves and boosts Special Attack by 1 stage when hit by an Electric-type move.'),
('Limber', 'Blocks paralysis.'),
('Liquid Ooze', 'Leeching moves cause the enemy to lose HP instead.'),
('Magic Bounce', 'Bounces back certain non-damaging moves.'),
('Magic Guard', 'Prevents indirect damage.'),
('Magician', 'If this Pokemon is not holding an item, it steals the held item of a target it hits with a move.'),
('Magma Armor', 'Cannot be frozen. Halves the amount of steps required to hatch Eggs.'),
('Magnet Pull', 'Prevents Steel-type Pokemon from switching. Increases the chance of encountering a Steel-type Pokemon in the wild.'),
('Marvel Scale', 'Boosts Defense 50% when afflicted by a non-volatile status.'),
('Mega Launcher', 'Boosts the power of Aura and Pulse moves, such as Aura Sphere and Dark Pulse, by 50%.'),
('Minus', 'If allied with a Pokemon with Plus or Minus, its Special Attack increases by 50%.'),
('Mold Breaker', 'Abilities that hinder attacks are nullified.'),
('Moody', 'A random stat is lowered by 1 stage and another is boosted by 2 stages every turn.'),
('Motor Drive', 'Grants immunity to Electric-type moves and boosts Speed by 1 stage when hit by a Electric-type move.'),
('Moxie', 'Boosts Attack by 1 stage if the wielder knocks out another Pokemon.'),
('Multiscale', 'Reduces damage by 50% if the wielder is at full health.'),
('Multitype', 'Type changes depending on the held plate. Prevents item loss.'),
('Mummy', 'The opponent''s ability becomes Mummy when it hits the wielder with a contact move.'),
('Natural Cure', 'Cures status on switching out.'),
('No Guard', 'All attacks used by and used on this Pokemon will never miss.'),
('Normalize', 'All moves used by this Pokemon become Normal-type.'),
('Oblivious', 'Grants immunity to infatuation, Captivate, and Taunt.'),
('Overcoat', 'Grants immunity to damage from weather effects and powder moves.'),
('Overgrow', 'Raises the power of Grass-type moves by 50% when at 1/3 HP or less.'),
('Own Tempo', 'Cannot be confused.'),
('Parental Bond', 'Allows the Pokemon to hit twice with the same move in one turn. Second hit has 0.5x base power. Does not affect Status, multihit, self-KO, or spread moves (in doubles).'),
('Pickpocket', 'The wielder immediately steals an item from an attacker using a contact move.'),
('Pickup', 'If the wielder has no held item, it gets the last item consumed at the end of the turn. Adds a chance of finding an item after each battle.'),
('Pixilate', 'Turns all of this Pokemon''s Normal-typed attacks into Fairy-type and deals 1.3x damage. Does not affect Hidden Power.'),
('Plus', 'If allied with a Pokemon with Plus or Minus, its Special Attack increases by 50%.'),
('Poison Heal', 'Heals 1/8 of max HP per turn when poisoned.'),
('Poison Point', 'Enemies'' contact moves have a 30% chance of poisoning them.'),
('Poison Touch', 'The wielder''s contact moves gain a 30% chance to poison the opponent.'),
('Prankster', 'Non-damaging moves have their priority increased by one level.'),
('Pressure', 'Enemy attacks lose 1 extra PP. Increases wild encounter rate.'),
('Primordial Sea', 'Summons Heavy Rain until Pokemon leaves battle. Fire-type moves and weather changing moves/abilities fail, except for Desolate Land and Delta Stream.'),
('Protean', 'Right before this Pokemon uses a move, it changes its type to match that move. Hidden Power is interpreted as its Hidden Power type, rather than Normal.'),
('Pure Power', 'Doubles Attack.'),
('Quick Feet', 'Increases Speed by 50% when afflicted with a status condition.'),
('Rain Dish', 'Heals 1/16 of max HP in rain.'),
('Rattled', 'Raises Speed one stage when hit by a Bug-, Dark-, or Ghost-type move.'),
('Reckless', 'Increases the power of recoil moves by 20%.'),
('Refrigerate', 'Turns all of this Pokemon''s Normal-typed attacks into Ice-typed and deal 1.3x damage. Does not affect Hidden Power.'),
('Regenerator', 'Wielder heals 1/3 of its maximum HP on switching out.'),
('Rivalry', 'Raises move power by 25% if the opponent has the same gender, and reduces by 25% if the opponent has the opposite gender. Genderless Pokemon do not affect this ability.'),
('Rock Head', 'Negates recoil from recoil moves.'),
('Rough Skin', 'Deals 1/8 recoil damage when the opponent makes contact.'),
('Run Away', 'Increases the chance of successfully escaping battle with a wild Pokemon.'),
('Sand Force', 'Increases power of Ground-, Rock-, and Steel-type attacks by 30% in a sandstorm.'),
('Sand Rush', 'Speed doubles in sandstorm.'),
('Sand Stream', 'Summons sandstorm.'),
('Sand Veil', 'Evasion increases by 20% in a sandstorm.'),
('Sap Sipper', 'Grants immunity to Grass-type moves and boosts Attack by 1 stage when hit by a Grass-type move.'),
('Scrappy', 'Can hit Ghost-types with Fighting- and Normal-type moves.'),
('Serene Grace', 'This Pokemon''s secondary effect chances are doubled.'),
('Shadow Tag', 'Traps opponents. Does not affect Pokemon with Shadow Tag.'),
('Shed Skin', '30% chance to heal status.'),
('Sheer Force', 'Increases power of moves with secondary effects by 30%, but removes the effects.'),
('Shell Armor', 'Prevents critical hits.'),
('Shield Dust', 'Secondary effects won''t occur.'),
('Simple', 'Doubles the effect of stat boosts and drops.'),
('Skill Link', 'Multi-hit moves will always hit the maximum number of times.'),
('Slow Start', 'Attack and Speed are halved for 5 turns.'),
('Sniper', 'Critical hits do 2.25x damage instead of 1.5x.'),
('Snow Cloak', 'Evasion increases by 20% in hail.'),
('Snow Warning', 'Summons hail.'),
('Solar Power', 'Loses 10% HP in sun each turn. Special Attack increases by 50%.'),
('Solid Rock', 'Reduces damage from super effective hits by 1/4.'),
('Soundproof', 'Unaffected by sound moves.'),
('Speed Boost', 'Speed raises at end of turn.'),
('Stall', 'This Pokemon moves last.'),
('Stance Change', 'Only affects Aegislash. If this Pokemon uses a Physical or Special move, it changes to Blade forme. If this Pokemon uses King''s Shield, it changes to Shield forme.'),
('Static', 'Enemies'' contact moves can paralyze them.'),
('Steadfast', 'Speed is boosted one stage when flinched.'),
('Stench', 'Adds a 10% flinch chance for moves that do not have one. Decreases wild encounter rate.'),
('Sticky Hold', 'This Pokemon''s item cannot be removed. Increases the chance of encountering Pokemon while fishing.'),
('Storm Drain', 'All Water-type attacks target this Pokemon. Grants immunity to Water-type moves and boosts Special Attack by 1 stage when hit by a Water-type move.'),
('Strong Jaw', 'This Pokemon receives a 50% power boost for jaw attacks such as Bite and Crunch.'),
('Sturdy', 'The wielder cannot be KO''d in one hit. OHKO moves will fail.'),
('Suction Cups', 'Cannot be forced to switch. Increases chance of encountering Pokemon while fishing.'),
('Super Luck', 'Critical hit rate increases one stage.'),
('Swarm', 'Boosts power of Bug-type moves by 50% when at 1/3 HP or less.'),
('Sweet Veil', 'Prevents allies from being put to Sleep.'),
('Swift Swim', 'Speed doubles in rain.'),
('Symbiosis', 'This Pokemon immediately passes its item to an ally after their item is consumed.'),
('Synchronize', 'When statused, the enemy is also statused. Can pass nature to wild Pokemon.'),
('Tangled Feet', 'Evasion increases when confused.'),
('Technician', 'Increases power of moves with 60 base power or less by 50%.'),
('Telepathy', 'Does not take damage from allies'' attacks.'),
('Teravolt', 'Abilities that hinder attacks are nullified.'),
('Thick Fat', 'Halves Ice- and Fire-type damage.'),
('Tinted Lens', 'Doubles damage on resisted hits.'),
('Torrent', 'Boosts power of Water-type moves by 50% when at 1/3 HP or less.'),
('Tough Claws', 'This Pokemon''s contact attacks do 1.33x damage.'),
('Toxic Boost', 'Attack is increased by 50% when poisoned.'),
('Trace', 'Copies foe''s ability.'),
('Truant', 'This Pokemon does nothing every other turn.'),
('Turboblaze', 'Abilities that hinder attacks are nullified.'),
('Unaware', 'Ignores stat boosts and debuffs on other Pokemon.'),
('Unburden', 'Speed increases when an item is used or lost.'),
('Unnerve', 'Prevents the foe from consuming its held Berry item.'),
('Victory Star', 'Increases the accuracy of the wielder and allies on its side of the field by 10%.'),
('Vital Spirit', 'Prevents sleep. Increases wild encounters with higher level Pokemon.'),
('Volt Absorb', 'Heals 25% HP when hit by an Electric-type attack.'),
('Water Absorb', 'Heals 25% HP when hit by a Water-type attack.'),
('Water Veil', 'Prevents burn.'),
('Weak Armor', 'Boosts Speed by 1 stage and lowers Defense by 1 stage when hit by a Physical move.'),
('White Smoke', 'Prevents the enemy from lowering this Pokemon''s stats and decreases wild encounter rate.'),
('Wonder Guard', 'Only super effective attacks harm this Pokemon.'),
('Wonder Skin', 'Reduces the accuracy of a status move to 50%.'),
('Zen Mode', 'The wielder changes forme when below 50% of its max HP.');